### ISSUE TITLE
PickUpMoney 1.8 Incompatible with MythicMobs 2.2.0 on Spigot 1.8.8

### ISSUE THREAD

**Issue by aleshkanet** [KickVN/PickupMoney#1]
```
[23:25:15] [Server thread/ERROR]: Could not pass event MythicMobDeathEvent to PickupMoney v1.8
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.elseland.xikage.MythicMobs.Adapters.Bukkit.Events.MobDeathListener.MobDeathEvent(MobDeathListener.java:159) [MythicMobs-2.2.0.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.EntitySkeleton.die(EntitySkeleton.java:142) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftSkeleton cannot be cast to org.bukkit.entity.Player
    at com.gmail.vkhanh234.PickupMoney.Listener.MythicMobsListener.onMobsDeath(MythicMobsListener.java:27) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-75593ab]
    ... 31 more
```

**Comment by kandoan** [comment]
Let try 1.8.1
