### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by Pigna** [KickVN/PickupMoney#14]
Plugin fails to load in 1.12

[17:27:25 INFO]: This server is running CraftBukkit version git-Spigot-99c2a37-3819f8d (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

[17:23:20 INFO]: [PickupMoney] Enabling PickupMoney v2.5.2
[17:23:20 ERROR]: Error occurred while enabling PickupMoney v2.5.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.FileConfiguration.load(Ljava/io/InputStream;)V
        at com.gmail.vkhanh234.PickupMoney.Config.Language.update(Language.java:33) ~[?:?]
        at com.gmail.vkhanh234.PickupMoney.Config.Language.<init>(Language.java:24) ~[?:?]
        at com.gmail.vkhanh234.PickupMoney.PickupMoney.initConfig(PickupMoney.java:312) ~[?:?]
        at com.gmail.vkhanh234.PickupMoney.PickupMoney.onEnable(PickupMoney.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-99c2a37-3819f8d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]

**Comment by blazex224** [comment]
I am having the same issue. Is this plugin still active?
